version: '3.9'
services: 
  database:
    platform: linux/x86_64
    image: mysql:8.0
    ports: 
      - '3306:3306'
    volumes: 
      - ./data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d'
    env_file: 
      - db.env
  
  backend:
    image: 'backend'
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend:/code
    ports: 
      - '5000:5000'
    environment:
      FLASK_ENV: development
    depends_on: 
      - 'database'

  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes: 
  #     - ./frontend:/app
  #   ports: 
  #     - '3000:3000'
  #   depends_on: 
  #     - 'backend'
